name: Update Judo RSS

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */3 * * *"

permissions:
  contents: write

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Create RSS feeds
        run: python make_rss.py

      - name: Save RSS feeds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add feeds/

          if git diff --cached --quiet; then
            echo "RSSに変更はありません"
          else
            git commit -m "Update RSS feeds"
            git push
          fi
